apiVersion: v1
kind: Secret
metadata:
  name: nodejs-secret
  namespace: default
type: Opaque
data:
  DB_USER: bXl1c2Vy
  DB_PASSWORD: bXlwYXNzd29yZA==
  DB_NAME: bXlkYXRhYmFzZQ==
  DB_HOST: cG9zdGdyZXM=
  DB_PORT: NTQzMg==
