apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: harinadhareddy/nodejs-app:latest
          envFrom:
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 3000